import React from 'react';
import classNames from 'classnames';
import { Inter, Poppins } from 'next/font/google';
import PropTypes from 'prop-types';

import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';

import 'swiper/css';
import 'swiper/swiper-bundle.css';
import 'react-toastify/dist/ReactToastify.css';
import './globals.scss';

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  RootLayout.propTypes = {
    children: PropTypes.node.isRequired,
  };

  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossOrigin="anonymous"
        />
      </head>
      <body className={classNames(poppins.variable, inter.variable)}>
        <Header />
        <div className={classNames('min-h-[40vh]')}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
